### ISSUE TITLE
Few models missed

### ISSUE THREAD

**Issue by ghost** [woelper/knives#1]
Next designs are listed in `README.md`, but those files a are missed:

- Andrew: https://github.com/woelper/knives/blob/master/knife_andrew/README.md
- Teo 2: https://github.com/woelper/knives/blob/master/knife_teo_2/README.md
- David: https://github.com/woelper/knives/blob/master/knife_david/README.md

**Comment by woelper** [comment]
Oh, thanks a lot for spotting! I'll correct that later!

**Comment by woelper** [comment]
Sorry for the delay, finally found the time. Also added more designs.
